language: go

# Faster container-based builds
sudo: false

go:
  - "1.11.x"
  - "1.12.x"
  -
env:
  global:
    - CGO_ENABLED=0
    - GORACE="halt_on_error=1"
    - GO111MODULE=on

install: true

script:
  - "CGO_ENABLED=1 go test --race --coverprofile=coverage.txt --covermode=atomic ./..."

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
